# CI pipeline for linting and tests
# - Lints the frontend React app using ESLint
# - Runs backend unit tests using Node's test runner

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    # Run all shell commands from the frontend folder by default
    defaults:
      run:
        working-directory: team-code-cruise/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20 and enable npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          # Use the frontend's lockfile for cache key
          cache-dependency-path: team-code-cruise/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        # If you want lint to only warn (not fail CI), add: --max-warnings=0

  frontend-test:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    # Run all shell commands from the frontend folder by default
    defaults:
      run:
        working-directory: team-code-cruise/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20 and enable npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          # Use the frontend's lockfile for cache key
          cache-dependency-path: team-code-cruise/frontend/package-lock.json

      - name: Install dependencies (allows new test deps)
        run: npm install
        # Using npm install instead of npm ci so CI can fetch newly added
        # devDependencies (e.g., vitest) without requiring an updated lockfile.
        # Once the lockfile is updated in the repo, switch back to `npm ci`.

      - name: Run frontend unit tests
        run: npm test

  backend-test:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    # Run all shell commands from the backend folder by default
    defaults:
      run:
        working-directory: team-code-cruise/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20 and enable npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          # Use the backend's lockfile for cache key
          cache-dependency-path: team-code-cruise/backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run prisma:gen
        # Tests use enums/types from @prisma/client; generation ensures availability

      - name: Run unit tests
        run: npm test
        # The test script sets RB_DATA_MODE=memory and JWT_SECRET=test-secret internally
